.TH "sources/ft_printf/specifiers Directory Reference" 3 "Infini-3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/ft_printf/specifiers Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBchar\&.c\fP"
.br
.ti -1c
.RI "file \fBdecimal\&.c\fP"
.br
.ti -1c
.RI "file \fBhex_lo\&.c\fP"
.br
.ti -1c
.RI "file \fBhex_up\&.c\fP"
.br
.ti -1c
.RI "file \fBinteger\&.c\fP"
.br
.ti -1c
.RI "file \fBpointer\&.c\fP"
.br
.ti -1c
.RI "file \fBstring\&.c\fP"
.br
.ti -1c
.RI "file \fBunsigned\&.c\fP"
.br
.in -1c
