.TH "sources/ft_printf/printers Directory Reference" 3 "Infini-3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/ft_printf/printers Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBhex\&.c\fP"
.br
.ti -1c
.RI "file \fBnumber\&.c\fP"
.br
.ti -1c
.RI "file \fBstring\&.c\fP"
.br
.in -1c
