.TH "sources/ft_printf/flags Directory Reference" 3 "Infini-3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/ft_printf/flags Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBalign_sign\&.c\fP"
.br
.ti -1c
.RI "file \fBforce_sign\&.c\fP"
.br
.ti -1c
.RI "file \fBhex_prefix\&.c\fP"
.br
.ti -1c
.RI "file \fBleft_justify\&.c\fP"
.br
.ti -1c
.RI "file \fBprecision\&.c\fP"
.br
.ti -1c
.RI "file \fBzero_padding\&.c\fP"
.br
.in -1c
