.TH "sources/ft_printf Directory Reference" 3 "Infini-3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/ft_printf Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBflags\fP"
.br
.ti -1c
.RI "directory \fBprinters\fP"
.br
.ti -1c
.RI "directory \fBspecifiers\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBft_printf\&.c\fP"
.br
.ti -1c
.RI "file \fButils\&.c\fP"
.br
.in -1c
