.TH "sources/libft/ft_itoa.c" 3 "Infini-3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/libft/ft_itoa.c
.SH SYNOPSIS
.br
.PP
\fC#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBitoa\fP (int _n, int len, char *out)"
.br
.ti -1c
.RI "char * \fBft_itoa\fP (int n)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2023 
.RE
.PP
\fBNote\fP
.RS 4
This function is part of the original libft\&. 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "char * ft_itoa (int n)"

.SS "static void itoa (int _n, int len, char * out)\fC [static]\fP"

.PP
\fBParameters\fP
.RS 4
\fI_n\fP 
.br
\fIlen\fP 
.br
\fIout\fP 
.RE
.PP
\fBAuthor\fP
.RS 4
amassias (amassias@42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBTodo\fP
.RS 4
Make documentation\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Infini-3D from the source code\&.
