.TH "sources/libft/ft_memswap.c" 3 "Infini-3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/libft/ft_memswap.c
.SH SYNOPSIS
.br
.PP
\fC#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBswap\fP (unsigned char *a, unsigned char *b)"
.br
.ti -1c
.RI "void \fBft_memswap\fP (void *_a, void *_b, size_t n)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2023 
.RE
.PP
\fBNote\fP
.RS 4
This function is part of the original libft\&. 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void ft_memswap (void * _a, void * _b, size_t n)"

.SS "static void swap (unsigned char * a, unsigned char * b)\fC [static]\fP"

.PP
\fBParameters\fP
.RS 4
\fIa\fP 
.br
\fIb\fP 
.RE
.PP
\fBAuthor\fP
.RS 4
amassias (amsssias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBTodo\fP
.RS 4
Make documentation\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Infini-3D from the source code\&.
