.TH "sources/libft/ft_putnbr_fd.c" 3 "Infini-3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/libft/ft_putnbr_fd.c
.SH SYNOPSIS
.br
.PP
\fC#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fB_ft_putnbr_fd\fP (unsigned int n, int fd)"
.br
.RI "Outputs the unsigned integer n to the given file descriptor\&. "
.ti -1c
.RI "void \fBft_putnbr_fd\fP (signed int _n, int fd)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2023 
.RE
.PP
\fBNote\fP
.RS 4
This function is part of the original libft\&. 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "static void _ft_putnbr_fd (unsigned int n, int fd)\fC [static]\fP"

.PP
Outputs the unsigned integer n to the given file descriptor\&. 
.PP
\fBParameters\fP
.RS 4
\fIn\fP The integer to output\&. 
.br
\fIfd\fP The file descriptor on which to write\&. 
.RE
.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP

.SS "void ft_putnbr_fd (signed int _n, int fd)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Infini-3D from the source code\&.
