.TH "sources/libft/ft_putendl_fd.c" 3 "Infini-3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/libft/ft_putendl_fd.c
.SH SYNOPSIS
.br
.PP
\fC#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBft_putendl_fd\fP (char *str, int fd)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2023 
.RE
.PP
\fBNote\fP
.RS 4
This function is part of the original libft\&. 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void ft_putendl_fd (char * str, int fd)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Infini-3D from the source code\&.
