.TH "sources/libft/ft_qsort.c" 3 "Infini-3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/libft/ft_qsort.c
.SH SYNOPSIS
.br
.PP
\fC#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static void * \fB_partition\fP (void *base, size_t nmemb, size_t size, t_comparator cmp)"
.br
.ti -1c
.RI "void \fBft_qsort\fP (void *base, size_t nmemb, size_t size, t_comparator cmp)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2023 
.RE
.PP
\fBNote\fP
.RS 4
This function is not part of the original libft\&. 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "static void * _partition (void * base, size_t nmemb, size_t size, t_comparator cmp)\fC [static]\fP"

.PP
\fBParameters\fP
.RS 4
\fIbase\fP 
.br
\fInmemb\fP 
.br
\fIsize\fP 
.br
\fIcmp\fP 
.RE
.PP
\fBReturns\fP
.RS 4
void* 
.RE
.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBTodo\fP
.RS 4
Make documentation\&. 
.RE
.PP

.SS "void ft_qsort (void * base, size_t nmemb, size_t size, t_comparator cmp)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Infini-3D from the source code\&.
