.TH "sources/ft_printf/printers/hex.c" 3 "Infini-3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/ft_printf/printers/hex.c
.SH SYNOPSIS
.br
.PP
\fC#include 'utils\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBU_CHARSET\fP   '0123456789ABCDEF0X'"
.br
.ti -1c
.RI "#define \fBL_CHARSET\fP   '0123456789abcdef0x'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static int \fB_len\fP (size_t n)"
.br
.ti -1c
.RI "static void \fB_print_hex\fP (const char *charset, size_t n)"
.br
.ti -1c
.RI "static void \fB_print\fP (\fBt_format\fP *fmt, size_t n, int pn, int u)"
.br
.ti -1c
.RI "int \fBhex_printer\fP (\fBt_format\fP *fmt, size_t n, int u)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2023 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define L_CHARSET   '0123456789abcdef0x'"

.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBTodo\fP
.RS 4
Make documentation\&. 
.RE
.PP

.SS "#define U_CHARSET   '0123456789ABCDEF0X'"

.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBTodo\fP
.RS 4
Make documentation\&. 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "static int _len (size_t n)\fC [static]\fP"

.PP
\fBParameters\fP
.RS 4
\fIn\fP 
.RE
.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBTodo\fP
.RS 4
Make documentation\&. 
.RE
.PP

.SS "static void _print (\fBt_format\fP * fmt, size_t n, int pn, int u)\fC [static]\fP"

.PP
\fBParameters\fP
.RS 4
\fIfmt\fP 
.br
\fIn\fP 
.br
\fIpn\fP 
.br
\fIu\fP 
.RE
.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBTodo\fP
.RS 4
Make documentation\&. 
.RE
.PP

.SS "static void _print_hex (const char * charset, size_t n)\fC [static]\fP"

.PP
\fBParameters\fP
.RS 4
\fIcharset\fP 
.br
\fIn\fP 
.RE
.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBTodo\fP
.RS 4
Make documentation\&. 
.RE
.PP

.SS "int hex_printer (\fBt_format\fP * fmt, size_t n, int u)"

.PP
\fBParameters\fP
.RS 4
\fIfmt\fP 
.br
\fIn\fP 
.br
\fIu\fP 
.RE
.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBTodo\fP
.RS 4
Make documentation\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Infini-3D from the source code\&.
