.TH "sources/ft_printf/printers/number.c" 3 "Infini-3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/ft_printf/printers/number.c
.SH SYNOPSIS
.br
.PP
\fC#include 'utils\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static int \fB_len\fP (long u)"
.br
.ti -1c
.RI "static void \fB_print_number\fP (unsigned long n)"
.br
.ti -1c
.RI "static void \fB_print\fP (\fBt_format\fP *fmt, long n, int pn)"
.br
.ti -1c
.RI "int \fBnumber_printer\fP (\fBt_format\fP *fmt, long n)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2023 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "static int _len (long u)\fC [static]\fP"

.PP
\fBParameters\fP
.RS 4
\fIu\fP 
.RE
.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBTodo\fP
.RS 4
Make documentation\&. 
.RE
.PP

.SS "static void _print (\fBt_format\fP * fmt, long n, int pn)\fC [static]\fP"

.PP
\fBParameters\fP
.RS 4
\fIfmt\fP 
.br
\fIn\fP 
.br
\fIpn\fP 
.RE
.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBTodo\fP
.RS 4
Make documentation\&. 
.RE
.PP

.SS "static void _print_number (unsigned long n)\fC [static]\fP"

.PP
\fBParameters\fP
.RS 4
\fIn\fP 
.RE
.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBTodo\fP
.RS 4
Make documentation\&. 
.RE
.PP

.SS "int number_printer (\fBt_format\fP * fmt, long n)"

.PP
\fBParameters\fP
.RS 4
\fIfmt\fP 
.br
\fIn\fP 
.RE
.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBTodo\fP
.RS 4
Make documentation\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Infini-3D from the source code\&.
