.TH "includes/ft_printf/utils.h" 3 "Infini-3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/ft_printf/utils.h
.SH SYNOPSIS
.br
.PP
\fC#include 'libft\&.h'\fP
.br
\fC#include <stdarg\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBs_format\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFMT_FLAG__LEFT_JUSTIFY\fP   0b000001"
.br
.ti -1c
.RI "#define \fBFMT_FLAG__FORCE_SIGN\fP   0b000010"
.br
.ti -1c
.RI "#define \fBFMT_FLAG__ALIGN_SIGN\fP   0b000100"
.br
.ti -1c
.RI "#define \fBFMT_FLAG__HEX_PREFIX\fP   0b001000"
.br
.ti -1c
.RI "#define \fBFMT_FLAG__ZERO_PADDING\fP   0b010000"
.br
.ti -1c
.RI "#define \fBFMT_FLAG__PRECISION\fP   0b100000"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBs_format\fP \fBt_format\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBputnchar\fP (char c, int count)"
.br
.ti -1c
.RI "int \fBmax\fP (int a, int b)"
.br
.ti -1c
.RI "int \fBmin\fP (int a, int b)"
.br
.ti -1c
.RI "int \fBfmt__left_justify\fP (\fBt_format\fP *fmt)"
.br
.ti -1c
.RI "int \fBfmt__force_sign\fP (\fBt_format\fP *fmt)"
.br
.ti -1c
.RI "int \fBfmt__align_sign\fP (\fBt_format\fP *fmt)"
.br
.ti -1c
.RI "int \fBfmt__hex_prefix\fP (\fBt_format\fP *fmt)"
.br
.ti -1c
.RI "int \fBfmt__zero_padding\fP (\fBt_format\fP *fmt)"
.br
.ti -1c
.RI "int \fBfmt__precision\fP (\fBt_format\fP *fmt)"
.br
.ti -1c
.RI "int \fBhex_printer\fP (\fBt_format\fP *fmt, size_t n, int u)"
.br
.ti -1c
.RI "int \fBstring_printer\fP (\fBt_format\fP *fmt, char *str)"
.br
.ti -1c
.RI "int \fBnumber_printer\fP (\fBt_format\fP *fmt, long n)"
.br
.ti -1c
.RI "int \fB_char_printer\fP (va_list *list, \fBt_format\fP *fmt)"
.br
.ti -1c
.RI "int \fB_string_printer\fP (va_list *list, \fBt_format\fP *fmt)"
.br
.ti -1c
.RI "int \fB_pointer_printer\fP (va_list *list, \fBt_format\fP *fmt)"
.br
.ti -1c
.RI "int \fB_decimal_printer\fP (va_list *list, \fBt_format\fP *fmt)"
.br
.ti -1c
.RI "int \fB_integer_printer\fP (va_list *list, \fBt_format\fP *fmt)"
.br
.ti -1c
.RI "int \fB_unsigned_printer\fP (va_list *list, \fBt_format\fP *fmt)"
.br
.ti -1c
.RI "int \fB_lo_hex_printer\fP (va_list *list, \fBt_format\fP *fmt)"
.br
.ti -1c
.RI "int \fB_up_hex_printer\fP (va_list *list, \fBt_format\fP *fmt)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FMT_FLAG__ALIGN_SIGN   0b000100"

.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBTodo\fP
.RS 4
Make documentation\&. 
.RE
.PP

.SS "#define FMT_FLAG__FORCE_SIGN   0b000010"

.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBTodo\fP
.RS 4
Make documentation\&. 
.RE
.PP

.SS "#define FMT_FLAG__HEX_PREFIX   0b001000"

.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBTodo\fP
.RS 4
Make documentation\&. 
.RE
.PP

.SS "#define FMT_FLAG__LEFT_JUSTIFY   0b000001"

.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBTodo\fP
.RS 4
Make documentation\&. 
.RE
.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBTodo\fP
.RS 4
Make documentation\&. 
.RE
.PP

.SS "#define FMT_FLAG__PRECISION   0b100000"

.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBTodo\fP
.RS 4
Make documentation\&. 
.RE
.PP

.SS "#define FMT_FLAG__ZERO_PADDING   0b010000"

.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBTodo\fP
.RS 4
Make documentation\&. 
.RE
.PP

.SH "Typedef Documentation"
.PP 
.SS "\fBt_format\fP"

.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBTodo\fP
.RS 4
Make documentation\&. 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int _char_printer (va_list * list, \fBt_format\fP * fmt)"

.PP
\fBParameters\fP
.RS 4
\fIlist\fP 
.br
\fIfmt\fP 
.RE
.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBTodo\fP
.RS 4
Make documentation\&. 
.RE
.PP

.SS "int _decimal_printer (va_list * list, \fBt_format\fP * fmt)"

.PP
\fBParameters\fP
.RS 4
\fIlist\fP 
.br
\fIfmt\fP 
.RE
.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBTodo\fP
.RS 4
Make documentation\&. 
.RE
.PP

.SS "int _integer_printer (va_list * list, \fBt_format\fP * fmt)"

.PP
\fBParameters\fP
.RS 4
\fIlist\fP 
.br
\fIfmt\fP 
.RE
.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBTodo\fP
.RS 4
Make documentation\&. 
.RE
.PP

.SS "int _lo_hex_printer (va_list * list, \fBt_format\fP * fmt)"

.PP
\fBParameters\fP
.RS 4
\fIlist\fP 
.br
\fIfmt\fP 
.RE
.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBTodo\fP
.RS 4
Make documentation\&. 
.RE
.PP

.SS "int _pointer_printer (va_list * list, \fBt_format\fP * fmt)"

.PP
\fBParameters\fP
.RS 4
\fIlist\fP 
.br
\fIfmt\fP 
.RE
.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBTodo\fP
.RS 4
Make documentation\&. 
.RE
.PP

.SS "int _string_printer (va_list * list, \fBt_format\fP * fmt)"

.PP
\fBParameters\fP
.RS 4
\fIlist\fP 
.br
\fIfmt\fP 
.RE
.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBTodo\fP
.RS 4
Make documentation\&. 
.RE
.PP

.SS "int _unsigned_printer (va_list * list, \fBt_format\fP * fmt)"

.PP
\fBParameters\fP
.RS 4
\fIlist\fP 
.br
\fIfmt\fP 
.RE
.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBTodo\fP
.RS 4
Make documentation\&. 
.RE
.PP

.SS "int _up_hex_printer (va_list * list, \fBt_format\fP * fmt)"

.PP
\fBParameters\fP
.RS 4
\fIlist\fP 
.br
\fIfmt\fP 
.RE
.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBTodo\fP
.RS 4
Make documentation\&. 
.RE
.PP

.SS "int fmt__align_sign (\fBt_format\fP * fmt)"

.PP
\fBParameters\fP
.RS 4
\fIfmt\fP 
.RE
.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBTodo\fP
.RS 4
Make documentation\&. 
.RE
.PP

.SS "int fmt__force_sign (\fBt_format\fP * fmt)"

.PP
\fBParameters\fP
.RS 4
\fIfmt\fP 
.RE
.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBTodo\fP
.RS 4
Make documentation\&. 
.RE
.PP

.SS "int fmt__hex_prefix (\fBt_format\fP * fmt)"

.PP
\fBParameters\fP
.RS 4
\fIfmt\fP 
.RE
.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBTodo\fP
.RS 4
Make documentation\&. 
.RE
.PP

.SS "int fmt__left_justify (\fBt_format\fP * fmt)"

.PP
\fBParameters\fP
.RS 4
\fIfmt\fP 
.RE
.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBTodo\fP
.RS 4
Make documentation\&. 
.RE
.PP

.SS "int fmt__precision (\fBt_format\fP * fmt)"

.PP
\fBParameters\fP
.RS 4
\fIfmt\fP 
.RE
.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBTodo\fP
.RS 4
Make documentation\&. 
.RE
.PP

.SS "int fmt__zero_padding (\fBt_format\fP * fmt)"

.PP
\fBParameters\fP
.RS 4
\fIfmt\fP 
.RE
.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBTodo\fP
.RS 4
Make documentation\&. 
.RE
.PP

.SS "int hex_printer (\fBt_format\fP * fmt, size_t n, int u)"

.PP
\fBParameters\fP
.RS 4
\fIfmt\fP 
.br
\fIn\fP 
.br
\fIu\fP 
.RE
.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBTodo\fP
.RS 4
Make documentation\&. 
.RE
.PP

.SS "int max (int a, int b)"

.PP
\fBParameters\fP
.RS 4
\fIa\fP 
.br
\fIb\fP 
.RE
.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBTodo\fP
.RS 4
Make documentation\&. 
.RE
.PP

.SS "int min (int a, int b)"

.PP
\fBParameters\fP
.RS 4
\fIa\fP 
.br
\fIb\fP 
.RE
.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBTodo\fP
.RS 4
Make documentation\&. 
.RE
.PP

.SS "int number_printer (\fBt_format\fP * fmt, long n)"

.PP
\fBParameters\fP
.RS 4
\fIfmt\fP 
.br
\fIn\fP 
.RE
.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBTodo\fP
.RS 4
Make documentation\&. 
.RE
.PP

.SS "void putnchar (char c, int count)"

.PP
\fBParameters\fP
.RS 4
\fIc\fP 
.br
\fIcount\fP 
.RE
.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBTodo\fP
.RS 4
Make documentation\&. 
.RE
.PP

.SS "int string_printer (\fBt_format\fP * fmt, char * str)"

.PP
\fBParameters\fP
.RS 4
\fIfmt\fP 
.br
\fIstr\fP 
.RE
.PP
\fBReturns\fP
.RS 4
int 
.RE
.PP
\fBAuthor\fP
.RS 4
amassias (amassias@student.42lehavre.fr) 
.RE
.PP
\fBDate\fP
.RS 4
2023-11-06 
.RE
.PP
\fBTodo\fP
.RS 4
Make documentation\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Infini-3D from the source code\&.
